"""
Django settings for openred project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j4%fow6!6o+e35fnjd&hpvvfhsud!llj=jlej5@mpcqkzdj7lg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

SITE_ID = 1

APPS_DIRS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Necesario para sites framework
    #'django_extensions', for model.png

    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth',  # Agregar el módulo principal
    'dj_rest_auth.registration',
    'rest_framework.authtoken',

    # Email backends
    'django_ses',

    # Other apps
    'rest_framework',
    'drf_yasg',
    'django_bootstrap5',

    # Custom apps
    'devices',
    'measures',
    'missions',
    'frontend',
    'users',  # Agregamos la app users
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Allauth middleware
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'openred.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': True,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'openred.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
##    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'openred_db',
        'USER': 'openred_user',
        'PASSWORD': 'openred',  # Cambiar por tu contraseña real
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Allauth settings
AUTHENTICATION_BACKENDS = [
    # Needed to log in by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods
    'allauth.account.auth_backends.AuthenticationBackend',
]
# No usar redirecciones HTML - todo se maneja via API
# LOGIN_REDIRECT_URL = '/'  # No necesario para API
# LOGOUT_REDIRECT_URL = '/'  # No necesario para API

# Email confirmation settings
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Options: "none", "optional", "mandatory"
ACCOUNT_EMAIL_REQUIRED = True

# Username behavior
ACCOUNT_USERNAME_REQUIRED = False  # If you want to log in with email only
ACCOUNT_AUTHENTICATION_METHOD = 'email'  # 'username' or 'username_email'
ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # No usar username
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

# Generar username automáticamente basado en email
ACCOUNT_ADAPTER = 'users.adapters.EmailUsernameAdapter'
ACCOUNT_USERNAME_VALIDATORS = []  # Eliminar validadores de username

# Desactivar redirecciones automáticas - usaremos React
# ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = 'http://localhost:3000/verify-email?key={key}'
# ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = 'http://localhost:3000/verify-email?key={key}'

# Configuración de URL personalizada para confirmación de email
ACCOUNT_CONFIRM_EMAIL_ON_GET = False  # No confirmar automáticamente con GET
ACCOUNT_EMAIL_CONFIRMATION_HMAC = False  # Usar el formato de key simple

# Social account settings - solo para API
SOCIALACCOUNT_QUERY_EMAIL = True
# SOCIALACCOUNT_LOGIN_ON_GET = True  # No necesario para API
# ACCOUNT_LOGOUT_REDIRECT_URL = "/"  # No necesario para API
# ACCOUNT_LOGOUT_ON_GET = True  # No necesario para API

# Amazon SES Email Configuration
EMAIL_BACKEND = 'django_ses.SESBackend'

# AWS Credentials (mejor usar IAM roles en producción)
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
AWS_SES_REGION_NAME = config('AWS_SES_REGION_NAME', default='us-east-1')  # Región donde está configurado SES
AWS_SES_REGION_ENDPOINT = f'email.{AWS_SES_REGION_NAME}.amazonaws.com'

# Configuración adicional de SES
AWS_SES_AUTO_THROTTLE = 0.5  # Limitar el envío para evitar rate limits
AWS_SES_CONFIGURATION_SET = config('AWS_SES_CONFIGURATION_SET', default=None)  # Opcional: para analytics

# Email settings
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@ibercivis.es')
SERVER_EMAIL = DEFAULT_FROM_EMAIL  # Para emails de error del servidor

# Fallback a console para desarrollo
if DEBUG and not AWS_ACCESS_KEY_ID:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Configuración de dj-rest-auth
REST_AUTH = {
    'REGISTER_SERIALIZER': 'users.serializers.CustomRegisterSerializer',
    'USER_DETAILS_SERIALIZER': 'users.serializers.UserSerializer',
    # Usar el serializador por defecto de dj-rest-auth para password reset
}

# Configuración para password reset
PASSWORD_RESET_TIMEOUT = 3600  # 1 hora para que expire el link

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Para tokens tradicionales de Django
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Para JWT
    ],
}

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'CLIENT_ID': config('GOOGLE_CLIENT_ID', default=''),  # Fetch from environment variable
        'SECRET': config('GOOGLE_CLIENT_SECRET', default=''),  # Fetch from environment variable
    }
}

# Mapbox
MAPBOX_ACCESS_TOKEN = config('MAPBOX_ACCESS_TOKEN', default='') # Fetch from environment variable
OSR_API_KEY = config('OSR_API_KEY', default='') # Fetch from environment variable



# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# URL to use when referring to static files located in STATIC_ROOT
STATIC_URL = '/static/'

# Directory where collectstatic will store static files
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional directories for static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # This is an optional folder for custom static files
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
