"""
Django settings for openred project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Frontend URL configuration
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

SITE_ID = 1

APPS_DIRS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Necesario para sites framework
    'django.contrib.gis',  # GeoDjango para soporte PostGIS
    'django_extensions', #for model.png
    
    # CORS headers
    'corsheaders',

    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth',  # Agregar el módulo principal
    'dj_rest_auth.registration',
    'rest_framework.authtoken',

    # Email backends
    'django_ses',

    # Other apps
    'rest_framework',
    'drf_spectacular',  # OpenAPI 3.0 schema generation
    'django_bootstrap5',
    'django_rq',  # RQ for background tasks

    # Custom apps
    'devices',
    'measures',
    'missions',
    'users',  # Agregamos la app users
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS debe ir ANTES de CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Allauth middleware
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'openred.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': True,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'openred.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
##    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',  # PostGIS backend for spatial support
        'NAME': config('DB_NAME', default='openred_db'),
        'USER': config('DB_USER', default='openred_user'),
        'PASSWORD': config('DB_PASSWORD', default='openred'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5434'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Allauth settings
AUTHENTICATION_BACKENDS = [
    # Needed to log in by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods
    'allauth.account.auth_backends.AuthenticationBackend',
]
# No usar redirecciones HTML - todo se maneja via API
# LOGIN_REDIRECT_URL = '/'  # No necesario para API
# LOGOUT_REDIRECT_URL = '/'  # No necesario para API

# Account settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Para registro tradicional
ACCOUNT_USERNAME_REQUIRED = False  # Login solo con email
ACCOUNT_AUTHENTICATION_METHOD = 'email'  # Login con email, no username
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'  # Usar username
ACCOUNT_CONFIRM_EMAIL_ON_GET = False  # No confirmar automáticamente con GET
ACCOUNT_EMAIL_CONFIRMATION_HMAC = False  # Usar formato de key simple

# Generar username automáticamente basado en email
ACCOUNT_ADAPTER = 'users.adapters.EmailUsernameAdapter'
SOCIALACCOUNT_ADAPTER = 'users.adapters.AutoConnectSocialAccountAdapter'
ACCOUNT_USERNAME_VALIDATORS = []  # Eliminar validadores de username

# Social account settings (Google OAuth)
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True  # Login/registro automático con Google
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Google ya verificó el email

# Amazon SES Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')

# AWS Credentials (mejor usar IAM roles en producción)
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
AWS_SES_REGION_NAME = config('AWS_SES_REGION_NAME', default='eu-central-1')  # Región donde está configurado SES
AWS_SES_REGION_ENDPOINT = config('AWS_SES_REGION_ENDPOINT', default=f'email.{AWS_SES_REGION_NAME}.amazonaws.com')

# Configuración adicional de SES
AWS_SES_AUTO_THROTTLE = 0.5  # Limitar el envío para evitar rate limits
AWS_SES_CONFIGURATION_SET = config('AWS_SES_CONFIGURATION_SET', default=None)  # Opcional: para analytics

# Email settings
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@ibercivis.es')
SERVER_EMAIL = config('SERVER_EMAIL', default='noreply@ibercivis.es')

# Configuración de dj-rest-auth
REST_AUTH = {
    'REGISTER_SERIALIZER': 'users.serializers.CustomRegisterSerializer',
    'PASSWORD_RESET_SERIALIZER': 'users.serializers.CustomPasswordResetSerializer',
    'USER_DETAILS_SERIALIZER': 'users.serializers.UserSerializer',
    'SESSION_LOGIN': False,  # Para API pura sin cookies de sesión
    'USE_JWT': False,  # Usar tokens en lugar de JWT
    'TOKEN_MODEL': 'rest_framework.authtoken.models.Token',
}

# Configuración para password reset
PASSWORD_RESET_TIMEOUT = 3600  # 1 hora para que expire el link

# ====================
# REST Framework Configuration
# ====================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # Para el browsable API
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # Lectura pública, escritura requiere autenticación
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # Use drf-spectacular for schema generation
}

# ====================
# API Documentation (drf-spectacular)
# ====================
SPECTACULAR_SETTINGS = {
    'TITLE': 'OpenRed API',
    'DESCRIPTION': 'API for managing environmental measurement data collection - radiation, light pollution, and more.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'CONTACT': {
        'name': 'Ibercivis - OpenRed Team',
        'email': 'frasanz@ibercivis.es',
        'url': 'https://github.com/Ibercivis/OpenRed',
    },
    'LICENSE': {
        'name': 'EUPL 1.2',
        'url': 'https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12',
    },
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/',
    'SECURITY': [{
        'tokenAuth': [],
    }],
    'SERVERS': [
        {'url': 'http://development.ibercivis.es:8000', 'description': 'Development server'},
        {'url': 'https://api.open-red.es', 'description': 'Production server'},
    ],
}

# ====================
# CORS Configuration
# ====================
if DEBUG:
    # Desarrollo: permitir todos los orígenes
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True
else:
    # Producción: solo FRONTEND_URL
    CORS_ALLOWED_ORIGINS = [config('FRONTEND_URL')]
    CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ====================
# CSRF Configuration
# ====================
if DEBUG:
    # Desarrollo: permitir acceso desde múltiples orígenes locales
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8001',
        'http://127.0.0.1:8001',
        'http://192.168.1.2:8001',
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://192.168.1.2:3000',
    ]
else:
    # Producción: solo FRONTEND_URL
    CSRF_TRUSTED_ORIGINS = [config('FRONTEND_URL')]

# ====================
# Social Auth Configuration
# ====================
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'VERIFIED_EMAIL': True,  # Asumir que los emails de Google están verificados
    }
}

# Mapbox
MAPBOX_ACCESS_TOKEN = config('MAPBOX_ACCESS_TOKEN', default='') # Fetch from environment variable
OSR_API_KEY = config('OSR_API_KEY', default='') # Fetch from environment variable

# ====================
# Security Settings (HTTPS/SSL - Production Only)
# ====================
if not DEBUG:
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True, cast=bool)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=True, cast=bool)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)



# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# URL to use when referring to static files located in STATIC_ROOT
STATIC_URL = '/static/'

# Directory where collectstatic will store static files
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional directories for static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # This is an optional folder for custom static files
]

# ====================
# Media Files Configuration
# ====================

# URL that handles the media served from MEDIA_ROOT
MEDIA_URL = '/media/'

# Absolute filesystem path to the directory that will hold user-uploaded files
MEDIA_ROOT = BASE_DIR / 'media'

# ====================
# RQ (Redis Queue) Configuration
# ====================

RQ_QUEUES = {
    'openred-tracks': {
        'HOST': config('REDIS_HOST', default='localhost'),
        'PORT': config('REDIS_PORT', default=6379, cast=int),
        'DB': config('REDIS_DB', default=0, cast=int),
        'DEFAULT_TIMEOUT': '10m',  # 10 minutes timeout for track processing
    },
    'openred-weather': {
        'HOST': config('REDIS_HOST', default='localhost'),
        'PORT': config('REDIS_PORT', default=6379, cast=int),
        'DB': config('REDIS_DB', default=0, cast=int),
        'DEFAULT_TIMEOUT': '30m',  # 30 minutes timeout for weather fetching
    },
}

# RQ Scheduler - Periodic tasks
# ====================
# Scheduled jobs will be executed by rqscheduler
# Run: python manage.py rqscheduler

RQ_SHOW_ADMIN_LINK = True  # Show RQ link in admin

# Scheduled jobs configuration
# To activate: python manage.py rqscheduler (in separate terminal)
from datetime import timedelta

RQ_JOBS = {
    'fetch_pending_weather': {
        'func': 'measures.tasks.fetch_pending_weather',
        'kwargs': {
            'limit': 100,  # Process up to 100 entries per run
            'max_attempts': 3,  # Skip entries with 3+ failed attempts
        },
        'interval': 60,  # Run every 60 seconds (1 minute for testing, use 3600 for production - 1 hour)
        'repeat': None,  # Repeat indefinitely
        'timeout': 300,  # 5 minute timeout
        'result_ttl': 500,  # Keep results for 500 seconds
    },
}

# ====================
# Default Settings
# ====================

# ====================
# Upload Limits
# ====================

_DEFAULT_TRACK_UPLOAD_MAX_POINTS = 20000
_DEFAULT_TRACK_UPLOAD_MAX_BYTES = 10 * 1024 * 1024  # 10 MiB

# Max number of points accepted in JSON track uploads
TRACK_UPLOAD_MAX_POINTS = config(
    'TRACK_UPLOAD_MAX_POINTS',
    default=_DEFAULT_TRACK_UPLOAD_MAX_POINTS,
    cast=int,
)

# Max request/file size accepted for track uploads
TRACK_UPLOAD_MAX_BYTES = config(
    'TRACK_UPLOAD_MAX_BYTES',
    default=_DEFAULT_TRACK_UPLOAD_MAX_BYTES,
    cast=int,
)

# Django global request upload limits (applies to all endpoints)
DATA_UPLOAD_MAX_MEMORY_SIZE = config(
    'DATA_UPLOAD_MAX_MEMORY_SIZE',
    default=TRACK_UPLOAD_MAX_BYTES,
    cast=int,
)
FILE_UPLOAD_MAX_MEMORY_SIZE = config(
    'FILE_UPLOAD_MAX_MEMORY_SIZE',
    default=TRACK_UPLOAD_MAX_BYTES,
    cast=int,
)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ====================
# Logging Configuration (for performance testing)
# ====================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'measures.views': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {  # Log ALL SQL queries
            'handlers': ['console'],
            'level': 'DEBUG',  # Cambia a INFO para desactivar queries SQL
            'propagate': False,
        },
    },
}
