# Generated by Django 4.2.17 on 2025-07-19 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('project_type', models.CharField(choices=[('radiation', 'Radiación Gamma'), ('light_pollution', 'Contaminación Lumínica')], max_length=20, verbose_name='Tipo de Proyecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_settings', models.JSONField(blank=True, default=dict, help_text='Configuración específica del proyecto en formato JSON')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Track')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('total_measurements', models.IntegerField(default=0, verbose_name='Total de Mediciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='missions.campaign', verbose_name='Campaña')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='devices.device', verbose_name='Dispositivo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='measures.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RadiationMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dateTime', models.DateTimeField(db_index=True, verbose_name='Fecha y Hora')),
                ('timestamp', models.BigIntegerField(blank=True, help_text='Unix timestamp', null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitud')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Altitud (m)')),
                ('accuracy', models.FloatField(blank=True, help_text='Precisión GPS en metros', null=True)),
                ('data_quality', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Buena'), ('fair', 'Regular'), ('poor', 'Pobre')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Observaciones adicionales sobre la medición', null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weather_fetched', models.BooleanField(default=False)),
                ('weather_fetch_attempts', models.IntegerField(default=0)),
                ('weather_last_attempt', models.DateTimeField(blank=True, null=True)),
                ('weather_data', models.JSONField(blank=True, help_text='Datos meteorológicos completos de OpenWeather', null=True)),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperatura (°C)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='Humedad (%)')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='Presión (hPa)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='Velocidad Viento (m/s)')),
                ('wind_direction', models.FloatField(blank=True, null=True, verbose_name='Dirección Viento (°)')),
                ('cloudiness', models.FloatField(blank=True, null=True, verbose_name='Nubosidad (%)')),
                ('weather_description', models.CharField(blank=True, max_length=100, verbose_name='Descripción Clima')),
                ('radiation_value', models.FloatField(help_text='Valor principal de radiación', verbose_name='Valor de Radiación')),
                ('radiation_unit', models.CharField(default='μSv/h', help_text='Unidad de medida de radiación', max_length=20, verbose_name='Unidad')),
                ('cpm', models.IntegerField(blank=True, help_text='Counts per minute', null=True, verbose_name='CPM')),
                ('dose_rate', models.FloatField(blank=True, help_text='Tasa de dosis equivalente', null=True, verbose_name='Tasa de Dosis')),
                ('detector_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Detector')),
                ('calibration_factor', models.FloatField(default=1.0, verbose_name='Factor de Calibración')),
                ('background_subtracted', models.BooleanField(default=False, help_text='Si se ha sustraído la radiación de fondo', verbose_name='Fondo Sustraído')),
                ('raw_data', models.JSONField(blank=True, help_text='Datos brutos del dispositivo en formato JSON', null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measures.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medición de Radiación',
                'verbose_name_plural': 'Mediciones de Radiación',
                'db_table': 'measures_radiation_measurement',
            },
        ),
        migrations.CreateModel(
            name='LightPollutionMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dateTime', models.DateTimeField(db_index=True, verbose_name='Fecha y Hora')),
                ('timestamp', models.BigIntegerField(blank=True, help_text='Unix timestamp', null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitud')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Altitud (m)')),
                ('accuracy', models.FloatField(blank=True, help_text='Precisión GPS en metros', null=True)),
                ('data_quality', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Buena'), ('fair', 'Regular'), ('poor', 'Pobre')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Observaciones adicionales sobre la medición', null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weather_fetched', models.BooleanField(default=False)),
                ('weather_fetch_attempts', models.IntegerField(default=0)),
                ('weather_last_attempt', models.DateTimeField(blank=True, null=True)),
                ('weather_data', models.JSONField(blank=True, help_text='Datos meteorológicos completos de OpenWeather', null=True)),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperatura (°C)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='Humedad (%)')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='Presión (hPa)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='Velocidad Viento (m/s)')),
                ('wind_direction', models.FloatField(blank=True, null=True, verbose_name='Dirección Viento (°)')),
                ('cloudiness', models.FloatField(blank=True, null=True, verbose_name='Nubosidad (%)')),
                ('weather_description', models.CharField(blank=True, max_length=100, verbose_name='Descripción Clima')),
                ('sky_brightness', models.FloatField(help_text='Brillo del cielo medido', verbose_name='Brillo del Cielo')),
                ('brightness_unit', models.CharField(default='mag/arcsec²', max_length=20, verbose_name='Unidad de Brillo')),
                ('sqm_reading', models.FloatField(blank=True, help_text='Sky Quality Meter reading', null=True, verbose_name='Lectura SQM')),
                ('nelm', models.FloatField(blank=True, help_text='Naked Eye Limiting Magnitude', null=True, verbose_name='NELM')),
                ('bortle_class', models.IntegerField(blank=True, choices=[(1, 'Clase 1'), (2, 'Clase 2'), (3, 'Clase 3'), (4, 'Clase 4'), (5, 'Clase 5'), (6, 'Clase 6'), (7, 'Clase 7'), (8, 'Clase 8'), (9, 'Clase 9')], help_text='Escala Bortle de Calidad del Cielo (1-9)', null=True, verbose_name='Clase Bortle')),
                ('moon_phase', models.FloatField(blank=True, help_text='Fase lunar (0.0 = Luna nueva, 1.0 = Luna llena)', null=True, verbose_name='Fase Lunar')),
                ('moon_altitude', models.FloatField(blank=True, help_text='Altitud de la luna sobre el horizonte (grados)', null=True, verbose_name='Altitud Lunar')),
                ('observation_angle', models.FloatField(blank=True, help_text='Ángulo de observación desde el cenit (grados)', null=True, verbose_name='Ángulo de Observación')),
                ('observation_direction', models.CharField(blank=True, choices=[('N', 'Norte'), ('NE', 'Noreste'), ('E', 'Este'), ('SE', 'Sureste'), ('S', 'Sur'), ('SW', 'Suroeste'), ('W', 'Oeste'), ('NW', 'Noroeste'), ('Z', 'Cenit')], max_length=10, verbose_name='Dirección de Observación')),
                ('measurement_data', models.JSONField(blank=True, help_text='Datos adicionales específicos de contaminación lumínica', null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measures.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medición de Contaminación Lumínica',
                'verbose_name_plural': 'Mediciones de Contaminación Lumínica',
                'db_table': 'measures_light_pollution_measurement',
            },
        ),
    ]
