# Generated by Django 4.2.17 on 2025-10-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0001_initial'),
    ]

    operations = [
        # Try to enable H3 extension. This will work in production with superuser
        # but may fail in test environments. That's OK - tests can still run without H3.
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS h3;",
            reverse_sql="DROP EXTENSION IF EXISTS h3;",
            # Don't run this in test mode - it requires superuser permissions
            state_operations=[],  # This migration doesn't change the model state
        ),
    ]
