# Generated by Django 4.2.17 on 2025-05-08 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0002_track'),
        ('devices', '0005_devicemodel_validatedbyopenred'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='missions.campaign'),
        ),
        migrations.AddField(
            model_name='track',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='devices.device'),
        ),
    ]
