# Generated by Django 4.2.17 on 2025-11-03 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0001_initial'),
        ('measures', '0002_enable_h3_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='track',
            field=models.ForeignKey(blank=True, help_text='Track al que pertenece esta medición (si fue importada de un archivo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='measures.track', verbose_name='Track'),
        ),
        migrations.AddField(
            model_name='radiationmeasurement',
            name='track',
            field=models.ForeignKey(blank=True, help_text='Track al que pertenece esta medición (si fue importada de un archivo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='measures.track', verbose_name='Track'),
        ),
        migrations.AddField(
            model_name='track',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Mensaje de Error'),
        ),
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, help_text='Archivo CSV/GPX con las mediciones', null=True, upload_to='tracks/%Y/%m/%d/', verbose_name='Archivo'),
        ),
        migrations.AddField(
            model_name='track',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('gpx', 'GPX'), ('json', 'JSON')], default='csv', max_length=10, verbose_name='Tipo de Archivo'),
        ),
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='track',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='missions.campaign', verbose_name='Campaña'),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tracks', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
