# Generated by Django 4.2.17 on 2025-11-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0003_lightpollutionmeasurement_track_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='name',
        ),
    ]
