# Generated by Django 4.2.17 on 2025-11-03 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measures', '0004_remove_track_name_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Optional campaign this measurement belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='missions.campaign', verbose_name='Campaign'),
        ),
        migrations.AddField(
            model_name='radiationmeasurement',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Optional campaign this measurement belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='missions.campaign', verbose_name='Campaign'),
        ),
        migrations.AlterField(
            model_name='lightpollutionmeasurement',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='lightpollutionmeasurement',
            name='project',
            field=models.ForeignKey(help_text='Parent project (required)', on_delete=django.db.models.deletion.CASCADE, to='measures.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='lightpollutionmeasurement',
            name='track',
            field=models.ForeignKey(blank=True, help_text='Track this measurement was imported from (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='measures.track', verbose_name='Track'),
        ),
        migrations.AlterField(
            model_name='lightpollutionmeasurement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='radiationmeasurement',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='radiationmeasurement',
            name='project',
            field=models.ForeignKey(help_text='Parent project (required)', on_delete=django.db.models.deletion.CASCADE, to='measures.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='radiationmeasurement',
            name='track',
            field=models.ForeignKey(blank=True, help_text='Track this measurement was imported from (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='measures.track', verbose_name='Track'),
        ),
        migrations.AlterField(
            model_name='radiationmeasurement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='track',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Optional campaign this track belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='missions.campaign', verbose_name='Campaign'),
        ),
        migrations.AlterField(
            model_name='track',
            name='device',
            field=models.ForeignKey(help_text='Device that captured the measurements', on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='devices.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='track',
            name='project',
            field=models.ForeignKey(help_text='Parent project (required)', on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='measures.project', verbose_name='Project'),
        ),
    ]
