# Generated by Django 4.2.17 on 2025-11-03 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_project_alter_mission_project'),
        ('measures', '0005_add_project_and_created_by_to_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightpollutionmeasurement',
            name='project',
            field=models.ForeignKey(help_text='Parent project (required)', on_delete=django.db.models.deletion.CASCADE, to='missions.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='radiationmeasurement',
            name='project',
            field=models.ForeignKey(help_text='Parent project (required)', on_delete=django.db.models.deletion.CASCADE, to='missions.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='track',
            name='project',
            field=models.ForeignKey(help_text='Parent project (required)', on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='missions.project', verbose_name='Project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
