# Generated by Django 4.2.17 on 2025-11-04 14:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0006_alter_lightpollutionmeasurement_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Punto geográfico para consultas espaciales (auto-generado desde lat/lng)', null=True, srid=4326, verbose_name='Ubicación Geográfica'),
        ),
        migrations.AddField(
            model_name='radiationmeasurement',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Punto geográfico para consultas espaciales (auto-generado desde lat/lng)', null=True, srid=4326, verbose_name='Ubicación Geográfica'),
        ),
        migrations.AddIndex(
            model_name='lightpollutionmeasurement',
            index=models.Index(fields=['location'], name='measures_li_locatio_3db7e9_idx'),
        ),
        migrations.AddIndex(
            model_name='radiationmeasurement',
            index=models.Index(fields=['location'], name='measures_ra_locatio_0dd8df_idx'),
        ),
    ]
