# Generated by Django 4.2.17 on 2025-11-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0007_lightpollutionmeasurement_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('gpx', 'GPX'), ('json', 'JSON'), ('rctrk', 'RCTRK')], default='csv', max_length=10, verbose_name='Tipo de Archivo'),
        ),
    ]
