# Generated by Django 4.2.17 on 2025-11-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0008_alter_track_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file_type',
            field=models.CharField(choices=[('rctrk', 'RCTRK')], default='rctrk', max_length=10, verbose_name='Tipo de Archivo'),
        ),
    ]
