# Generated by Django 4.2.17 on 2025-11-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0009_alter_track_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiationmeasurement',
            name='radiation_value',
        ),
    ]
