# Generated by Django 4.2.17 on 2025-11-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_project_alter_mission_project'),
        ('measures', '0010_remove_radiation_value_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='mission',
            field=models.ForeignKey(blank=True, help_text='Optional mission this track belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='missions.mission', verbose_name='Mission'),
        ),
    ]
