# Generated by Django 4.2.17 on 2025-11-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0011_track_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightpollutionmeasurement',
            name='track',
            field=models.ForeignKey(blank=True, help_text='Track this measurement was imported from (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='measures.track', verbose_name='Track'),
        ),
        migrations.AlterField(
            model_name='radiationmeasurement',
            name='track',
            field=models.ForeignKey(blank=True, help_text='Track this measurement was imported from (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='measures.track', verbose_name='Track'),
        ),
    ]
