# Generated by Django 4.2.17 on 2025-11-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0012_alter_lightpollutionmeasurement_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiationmeasurement',
            name='speed',
            field=models.FloatField(blank=True, help_text='Speed in m/s calculated from GPS positions', null=True, verbose_name='Speed'),
        ),
        migrations.AddField(
            model_name='track',
            name='average_speed',
            field=models.FloatField(blank=True, help_text='Average speed of the track in m/s', null=True, verbose_name='Average Speed'),
        ),
    ]
