# Generated by Django 4.2.17 on 2025-11-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0013_radiationmeasurement_speed_track_average_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='total_distance',
            field=models.FloatField(blank=True, help_text='Total distance traveled in meters', null=True, verbose_name='Total Distance'),
        ),
    ]
