# Generated by Django 4.2.17 on 2025-11-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0014_add_total_distance_to_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='avg_dose_rate',
            field=models.FloatField(blank=True, help_text='Average dose rate in μSv/h', null=True, verbose_name='Average Dose Rate'),
        ),
        migrations.AddField(
            model_name='track',
            name='max_dose_rate',
            field=models.FloatField(blank=True, help_text='Maximum dose rate in μSv/h', null=True, verbose_name='Maximum Dose Rate'),
        ),
        migrations.AddField(
            model_name='track',
            name='min_dose_rate',
            field=models.FloatField(blank=True, help_text='Minimum dose rate in μSv/h', null=True, verbose_name='Minimum Dose Rate'),
        ),
        migrations.AddField(
            model_name='track',
            name='std_dose_rate',
            field=models.FloatField(blank=True, help_text='Standard deviation of dose rate in μSv/h', null=True, verbose_name='Dose Rate Std Deviation'),
        ),
    ]
