# Generated by Django 4.2.17 on 2025-11-08 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0015_add_radiation_stats_to_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightpollutionmeasurement',
            name='cloudiness',
        ),
        migrations.RemoveField(
            model_name='lightpollutionmeasurement',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='lightpollutionmeasurement',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='lightpollutionmeasurement',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='lightpollutionmeasurement',
            name='weather_data',
        ),
        migrations.RemoveField(
            model_name='lightpollutionmeasurement',
            name='weather_description',
        ),
        migrations.RemoveField(
            model_name='lightpollutionmeasurement',
            name='weather_fetch_attempts',
        ),
        migrations.RemoveField(
            model_name='lightpollutionmeasurement',
            name='weather_fetched',
        ),
        migrations.RemoveField(
            model_name='lightpollutionmeasurement',
            name='weather_last_attempt',
        ),
        migrations.RemoveField(
            model_name='lightpollutionmeasurement',
            name='wind_direction',
        ),
        migrations.RemoveField(
            model_name='lightpollutionmeasurement',
            name='wind_speed',
        ),
        migrations.RemoveField(
            model_name='radiationmeasurement',
            name='cloudiness',
        ),
        migrations.RemoveField(
            model_name='radiationmeasurement',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='radiationmeasurement',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='radiationmeasurement',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='radiationmeasurement',
            name='weather_data',
        ),
        migrations.RemoveField(
            model_name='radiationmeasurement',
            name='weather_description',
        ),
        migrations.RemoveField(
            model_name='radiationmeasurement',
            name='weather_fetch_attempts',
        ),
        migrations.RemoveField(
            model_name='radiationmeasurement',
            name='weather_fetched',
        ),
        migrations.RemoveField(
            model_name='radiationmeasurement',
            name='weather_last_attempt',
        ),
        migrations.RemoveField(
            model_name='radiationmeasurement',
            name='wind_direction',
        ),
        migrations.RemoveField(
            model_name='radiationmeasurement',
            name='wind_speed',
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h3_cell', models.CharField(db_index=True, help_text='H3 hexagonal cell index (resolution 8 = ~5.5km)', max_length=20, verbose_name='H3 Cell')),
                ('timestamp_hour', models.DateTimeField(db_index=True, help_text='Hour-rounded timestamp for time window grouping', verbose_name='Timestamp (Hour)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Representative latitude for this H3 cell', max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Representative longitude for this H3 cell', max_digits=11, null=True, verbose_name='Longitude')),
                ('weather_data', models.JSONField(blank=True, help_text='Complete weather response from Open-Meteo API', null=True, verbose_name='Weather Data')),
                ('temperature', models.FloatField(blank=True, help_text='Temperature at 2 meters (temperature_2m)', null=True, verbose_name='Temperature (°C)')),
                ('humidity', models.FloatField(blank=True, help_text='Relative humidity at 2 meters (relative_humidity_2m)', null=True, verbose_name='Relative Humidity (%)')),
                ('pressure', models.FloatField(blank=True, help_text='Atmospheric pressure at sea level (pressure_msl)', null=True, verbose_name='Pressure (hPa)')),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind speed at 10 meters (wind_speed_10m)', null=True, verbose_name='Wind Speed (km/h)')),
                ('wind_direction', models.FloatField(blank=True, help_text='Wind direction at 10 meters (wind_direction_10m)', null=True, verbose_name='Wind Direction (°)')),
                ('cloud_cover', models.FloatField(blank=True, help_text='Total cloud cover percentage', null=True, verbose_name='Cloud Cover (%)')),
                ('fetch_attempts', models.IntegerField(default=0, verbose_name='Fetch Attempts')),
                ('last_fetch_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Last Fetch Attempt')),
                ('fetched', models.BooleanField(db_index=True, default=False, verbose_name='Data Fetched')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather Cache',
                'verbose_name_plural': 'Weather Cache Entries',
                'ordering': ['-timestamp_hour'],
                'indexes': [models.Index(fields=['h3_cell', 'timestamp_hour'], name='measures_we_h3_cell_0dadab_idx'), models.Index(fields=['fetched'], name='measures_we_fetched_3661e7_idx'), models.Index(fields=['timestamp_hour'], name='measures_we_timesta_7373d9_idx')],
                'unique_together': {('h3_cell', 'timestamp_hour')},
            },
        ),
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='weather_cache',
            field=models.ForeignKey(blank=True, help_text="Cached weather data for this measurement's H3 cell + time window", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='measures.weathercache', verbose_name='Weather Cache'),
        ),
        migrations.AddField(
            model_name='radiationmeasurement',
            name='weather_cache',
            field=models.ForeignKey(blank=True, help_text="Cached weather data for this measurement's H3 cell + time window", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='measures.weathercache', verbose_name='Weather Cache'),
        ),
    ]
