# Generated by Django 4.2.17 on 2025-12-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0016_add_weather_cache_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cloud_track_id',
            field=models.CharField(blank=True, help_text='Track ID from cloud/mobile app', max_length=100, null=True, verbose_name='Cloud Track ID'),
        ),
        migrations.AddField(
            model_name='track',
            name='required_gps_accuracy_meters',
            field=models.FloatField(blank=True, help_text='Required GPS accuracy in meters for this track', null=True, verbose_name='Required GPS Accuracy'),
        ),
        migrations.AddField(
            model_name='track',
            name='synced',
            field=models.BooleanField(blank=True, default=False, help_text='Track synced status from mobile app', null=True, verbose_name='Synced'),
        ),
        migrations.AddField(
            model_name='track',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='When track was synced to cloud', null=True, verbose_name='Synced At'),
        ),
        migrations.AlterField(
            model_name='track',
            name='file_type',
            field=models.CharField(choices=[('rctrk', 'RCTRK'), ('json', 'JSON')], default='rctrk', max_length=10, verbose_name='Tipo de Archivo'),
        ),
    ]
