# Generated by Django 4.2.17 on 2025-12-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0017_track_cloud_track_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiationmeasurement',
            name='cpm_error',
            field=models.FloatField(blank=True, help_text='Absolute error of CPM measurement', null=True, verbose_name='CPM Error'),
        ),
        migrations.AddField(
            model_name='radiationmeasurement',
            name='dose_rate_error',
            field=models.FloatField(blank=True, help_text='Absolute error of dose rate measurement', null=True, verbose_name='Dose Rate Error'),
        ),
    ]
