# Generated by Django 4.2.17 on 2026-01-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0018_add_error_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathercache',
            name='rain_sum',
            field=models.FloatField(blank=True, help_text='Total daily precipitation sum (rain_sum)', null=True, verbose_name='Rain Sum (mm)'),
        ),
    ]
