# Generated by GitHub Copilot

from django.db import migrations, models


def move_legacy_lightpollution_fields(apps, schema_editor):
    LightPollutionMeasurement = apps.get_model('measures', 'LightPollutionMeasurement')

    legacy_field_names = [
        'sky_brightness',
        'brightness_unit',
        'sqm_reading',
        'nelm',
        'bortle_class',
        'moon_phase',
        'moon_altitude',
        'observation_angle',
        'observation_direction',
        'measurement_data',
    ]

    for measurement in LightPollutionMeasurement.objects.all().iterator():
        legacy_data = {}
        for field_name in legacy_field_names:
            if hasattr(measurement, field_name):
                legacy_data[field_name] = getattr(measurement, field_name)
        measurement.legacy_data = legacy_data
        measurement.save(update_fields=['legacy_data'])


def noop_reverse(apps, schema_editor):
    # Keeping legacy_data is intentional; we don't restore removed columns.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0019_weathercache_rain_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='legacy_data',
            field=models.JSONField(blank=True, default=dict, help_text='Legacy fields preserved during schema migrations'),
        ),
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='lux',
            field=models.FloatField(blank=True, null=True, verbose_name='Lux'),
        ),
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='cct',
            field=models.FloatField(blank=True, null=True, verbose_name='CCT'),
        ),
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='cieX',
            field=models.FloatField(blank=True, null=True, verbose_name='CIE x'),
        ),
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='cieY',
            field=models.FloatField(blank=True, null=True, verbose_name='CIE y'),
        ),
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='cieU',
            field=models.FloatField(blank=True, null=True, verbose_name='CIE u'),
        ),
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='cieV',
            field=models.FloatField(blank=True, null=True, verbose_name='CIE v'),
        ),
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='duv',
            field=models.FloatField(blank=True, null=True, verbose_name='Duv'),
        ),
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='tint',
            field=models.FloatField(blank=True, null=True, verbose_name='Tint'),
        ),
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='mode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='channels',
            field=models.JSONField(blank=True, null=True, verbose_name='Channels'),
        ),
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='batteryMv',
            field=models.IntegerField(blank=True, null=True, verbose_name='Battery (mV)'),
        ),
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Speed'),
        ),
        migrations.RunPython(move_legacy_lightpollution_fields, reverse_code=noop_reverse),
        migrations.RemoveField(model_name='lightpollutionmeasurement', name='sky_brightness'),
        migrations.RemoveField(model_name='lightpollutionmeasurement', name='brightness_unit'),
        migrations.RemoveField(model_name='lightpollutionmeasurement', name='sqm_reading'),
        migrations.RemoveField(model_name='lightpollutionmeasurement', name='nelm'),
        migrations.RemoveField(model_name='lightpollutionmeasurement', name='bortle_class'),
        migrations.RemoveField(model_name='lightpollutionmeasurement', name='moon_phase'),
        migrations.RemoveField(model_name='lightpollutionmeasurement', name='moon_altitude'),
        migrations.RemoveField(model_name='lightpollutionmeasurement', name='observation_angle'),
        migrations.RemoveField(model_name='lightpollutionmeasurement', name='observation_direction'),
        migrations.RemoveField(model_name='lightpollutionmeasurement', name='measurement_data'),
    ]
