# Generated by Django 4.2.17 on 2026-03-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0020_lightpollutionmeasurement_json_schema'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='radiationmeasurement',
            index=models.Index(fields=['altitude'], name='measures_ra_altitude_idx'),
        ),
        migrations.AddIndex(
            model_name='lightpollutionmeasurement',
            index=models.Index(fields=['altitude'], name='measures_li_altitude_idx'),
        ),
        migrations.AddIndex(
            model_name='lightpollutionmeasurement',
            index=models.Index(fields=['lux'], name='measures_li_lux_081957_idx'),
        ),
        migrations.AddIndex(
            model_name='lightpollutionmeasurement',
            index=models.Index(fields=['speed'], name='measures_li_speed_c582f2_idx'),
        ),
        migrations.AddIndex(
            model_name='radiationmeasurement',
            index=models.Index(fields=['dose_rate'], name='measures_ra_dose_ra_627309_idx'),
        ),
        migrations.AddIndex(
            model_name='radiationmeasurement',
            index=models.Index(fields=['speed'], name='measures_ra_speed_e09235_idx'),
        ),
    ]
