# Generated by Django 4.2.17 on 2026-04-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0022_track_track_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lightpollutionmeasurement',
            name='measures_li_altitude_idx',
        ),
        migrations.RemoveIndex(
            model_name='radiationmeasurement',
            name='measures_ra_altitude_idx',
        ),
    ]
