# Generated by Django 4.2.17 on 2026-05-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0023_remove_lightpollutionmeasurement_measures_li_altitude_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('index', models.IntegerField(help_text='0-based order within the track', verbose_name='Índice')),
                ('started_at', models.DateTimeField(verbose_name='Inicio de captura')),
                ('ended_at', models.DateTimeField(verbose_name='Fin de captura')),
                ('duration_sec', models.IntegerField(help_text='Integration (live) time in seconds', verbose_name='Duración (s)')),
                ('a0', models.FloatField(verbose_name='Calibración a0')),
                ('a1', models.FloatField(verbose_name='Calibración a1')),
                ('a2', models.FloatField(verbose_name='Calibración a2')),
                ('channel_count', models.IntegerField(verbose_name='Nº de canales')),
                ('counts', models.JSONField(help_text='Accumulated counts per channel (len == channel_count)', verbose_name='Cuentas por canal')),
                ('start_lat', models.FloatField(blank=True, null=True, verbose_name='Latitud inicio')),
                ('start_lon', models.FloatField(blank=True, null=True, verbose_name='Longitud inicio')),
                ('start_alt', models.FloatField(blank=True, null=True, verbose_name='Altitud inicio (m)')),
                ('end_lat', models.FloatField(blank=True, null=True, verbose_name='Latitud fin')),
                ('end_lon', models.FloatField(blank=True, null=True, verbose_name='Longitud fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(help_text='Track this spectrum was integrated over', on_delete=django.db.models.deletion.CASCADE, related_name='spectra', to='measures.track', verbose_name='Track')),
            ],
            options={
                'verbose_name': 'Espectro',
                'verbose_name_plural': 'Espectros',
                'ordering': ['track', 'index'],
                'indexes': [models.Index(fields=['track', 'index'], name='measures_sp_track_i_5f441b_idx')],
            },
        ),
    ]
