# Generated by Django 4.2.17 on 2026-05-30 16:23

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_add_campaign_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0002_device_ingest_token_created_at_and_more'),
        ('measures', '0024_spectrum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Estación')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitud')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Altitud (m)')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Punto geográfico (auto-generado desde lat/lng)', null=True, srid=4326, verbose_name='Ubicación Geográfica')),
                ('expected_interval_seconds', models.PositiveIntegerField(default=300, help_text='Segundos esperados entre medidas (default 300 = 5 min)', verbose_name='Intervalo Esperado (s)')),
                ('last_measurement_at', models.DateTimeField(blank=True, help_text='Hora de llegada al servidor de la última medida (para el watchdog)', null=True, verbose_name='Última Medida')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estación',
                'verbose_name_plural': 'Estaciones',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='radiationmeasurement',
            name='capture_mode',
            field=models.CharField(choices=[('movement', 'Movement'), ('static', 'Static')], default='movement', help_text='movement: punto suelto a agrupar en track / static: serie temporal de una estación', max_length=20, verbose_name='Modo de Captura'),
        ),
        migrations.AddField(
            model_name='radiationmeasurement',
            name='received_at',
            field=models.DateTimeField(blank=True, help_text='Hora de llegada al servidor (independiente del reloj del aparato)', null=True, verbose_name='Recibido en'),
        ),
        migrations.AddIndex(
            model_name='radiationmeasurement',
            index=models.Index(fields=['capture_mode', 'track', 'device'], name='measures_ra_capture_7a86c3_idx'),
        ),
        migrations.AddField(
            model_name='station',
            name='device',
            field=models.OneToOneField(help_text='Hardware device bound 1:1 to this station', on_delete=django.db.models.deletion.CASCADE, related_name='station', to='devices.device', verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='station',
            name='project',
            field=models.ForeignKey(help_text='Project all station readings are filed under', on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='missions.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='station',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='radiationmeasurement',
            name='station',
            field=models.ForeignKey(blank=True, help_text='Estación base que emitió esta medida (solo para capture_mode=static)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='measures.station', verbose_name='Estación'),
        ),
        migrations.AddIndex(
            model_name='radiationmeasurement',
            index=models.Index(fields=['station'], name='measures_ra_station_3bc32b_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['status'], name='measures_st_status_037e71_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['last_measurement_at'], name='measures_st_last_me_483aa6_idx'),
        ),
    ]
