# Generated by Django 4.2.17 on 2026-05-30 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_created_at_device_updated_at'),
        ('measures', '0025_station_radiationmeasurement_capture_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightpollutionmeasurement',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='radiationmeasurement',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='track',
            name='device',
            field=models.ForeignKey(help_text='Device that captured the measurements', on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='devices.device', verbose_name='Device'),
        ),
    ]
