# Generated by Django 4.2.17 on 2026-07-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0026_alter_lightpollutionmeasurement_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiationmeasurement',
            name='cpm_rel_error',
            field=models.FloatField(blank=True, help_text='Relative error of CPM (fraction, e.g. 0.18 = 18%)', null=True, verbose_name='CPM Relative Error'),
        ),
        migrations.AddField(
            model_name='radiationmeasurement',
            name='dose_rate_rel_error',
            field=models.FloatField(blank=True, help_text='Relative error of dose rate (fraction, e.g. 0.09 = 9%)', null=True, verbose_name='Dose Rate Relative Error'),
        ),
    ]
