# Generated by Django 4.2.17 on 2026-07-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0027_radiationmeasurement_cpm_rel_error_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='radiationmeasurement',
            index=models.Index(fields=['station', 'dateTime'], name='measures_ra_station_41a58d_idx'),
        ),
    ]
