# Generated by Django 4.2.17 on 2026-09-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0028_radiationmeasurement_measures_ra_station_41a58d_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.PositiveIntegerField(help_text='Número de contribuciones del hito (p.ej. 300000)', unique=True, verbose_name='Umbral')),
                ('total_at_detection', models.PositiveIntegerField(verbose_name='Contribuciones al detectarlo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de envío'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('backfilled', 'Registrado sin envío (ya superado)'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Detectado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Destinatarios')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Fallos de envío')),
                ('error_message', models.TextField(blank=True, verbose_name='Error')),
            ],
            options={
                'verbose_name': 'Hito de contribuciones',
                'verbose_name_plural': 'Hitos de contribuciones',
                'ordering': ['-threshold'],
            },
        ),
    ]
