# Generated by Django 4.2.17 on 2026-10-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0029_contributionmilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightpollutionmeasurement',
            name='urban_class',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Degree of Urbanisation code from the GHS-SMOD grid; see measures/urban_class.py', null=True, verbose_name='Urban class (GHS-SMOD)'),
        ),
    ]
