# Generated by Django 4.2.17 on 2026-05-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ingest_token_created_at',
            field=models.DateTimeField(blank=True, help_text='When the current ingest token was issued/rotated', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='ingest_token_hash',
            field=models.CharField(blank=True, db_index=True, help_text="SHA-256 hash of the device's ingest token (plaintext never stored)", max_length=64, null=True, unique=True),
        ),
    ]
