# Generated by Django 4.2.17 on 2025-11-03 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('measures', '0005_add_project_and_created_by_to_mission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-start_date'], 'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-start_date'], 'verbose_name': 'Mission', 'verbose_name_plural': 'Missions'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='mission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_missions', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='mission',
            name='project',
            field=models.ForeignKey(default=1, help_text='Parent project this mission belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='measures.project', verbose_name='Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='devices',
            field=models.ManyToManyField(blank=True, help_text='Devices used in this campaign', related_name='campaigns', to='devices.device', verbose_name='Devices'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='mission',
            field=models.ForeignKey(help_text='Parent mission this campaign belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='missions.mission', verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Campaign Name'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Users participating in this campaign', related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Mission Name'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('mission', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='mission',
            unique_together={('project', 'name')},
        ),
    ]
