# Generated by Django 4.2.17 on 2025-11-03 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_projects_data(apps, schema_editor):
    """
    Copy all data from measures_project to missions_project
    """
    db_alias = schema_editor.connection.alias
    
    # Get the connection cursor
    with schema_editor.connection.cursor() as cursor:
        # Copy all data from measures_project to missions_project
        cursor.execute("""
            INSERT INTO missions_project 
            (id, name, description, project_type, is_active, is_public, created_at, updated_at, project_settings, created_by_id)
            SELECT id, name, description, project_type, is_active, is_public, created_at, updated_at, project_settings, created_by_id
            FROM measures_project;
        """)
        
        # Update the sequence for the missions_project table to continue from the last ID
        cursor.execute("""
            SELECT setval('missions_project_id_seq', (SELECT MAX(id) FROM missions_project));
        """)


def reverse_copy_projects_data(apps, schema_editor):
    """
    Reverse migration: copy back from missions_project to measures_project
    """
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        # Copy back from missions_project to measures_project
        cursor.execute("""
            INSERT INTO measures_project 
            (id, name, description, project_type, is_active, is_public, created_at, updated_at, project_settings, created_by_id)
            SELECT id, name, description, project_type, is_active, is_public, created_at, updated_at, project_settings, created_by_id
            FROM missions_project;
        """)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missions', '0002_add_project_and_created_by_to_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('project_type', models.CharField(choices=[('radiation', 'Radiación Gamma'), ('light_pollution', 'Contaminación Lumínica')], max_length=20, verbose_name='Tipo de Proyecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_settings', models.JSONField(blank=True, default=dict, help_text='Configuración específica del proyecto en formato JSON')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['name'],
            },
        ),
        # Copy data from measures_project to missions_project
        migrations.RunPython(copy_projects_data, reverse_copy_projects_data),
        migrations.AlterField(
            model_name='mission',
            name='project',
            field=models.ForeignKey(help_text='Parent project this mission belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='missions.project', verbose_name='Project'),
        ),
    ]
