# Generated by Django 4.2.17 on 2025-11-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_project_alter_mission_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='devices',
        ),
    ]
