# Generated by Django 4.2.17 on 2025-12-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_remove_campaign_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='password',
            field=models.CharField(blank=True, help_text='Optional password to protect track uploads to this campaign', max_length=255, null=True, verbose_name='Password'),
        ),
    ]
